// engine_core/src/ecs/ecs.rs
use crate::ecs::component::*;
use crate::ecs::component_registry::*;
use crate::ecs::entity::*;
use crate::ecs::has_any::HasAny;
use crate::ecs::transform::Transform;
use crate::game::GameCtxMut;
use crate::worlds::room::RoomId;
use once_cell::sync::Lazy;
use serde::de::Deserializer;
use serde::ser::{SerializeStruct, Serializer};
use serde::{Deserialize, Serialize};
use std::any::Any;
use std::any::TypeId;
use std::collections::HashMap;

#[derive(Default, Debug)]
pub struct Ecs {
    pub stores: HashMap<TypeId, Box<dyn Any + Send + Sync>>,
    next_entity_id: usize,
}

impl Ecs {
    /// Allocate a fresh id and return a builder.
    pub fn create_entity(&mut self) -> EntityBuilder<'_> {
        // This ensures id will always start from 1
        self.next_entity_id += 1;
        EntityBuilder {
            id: Entity(self.next_entity_id),
            ecs: self,
        }
    }

    /// Immutable reference to a component belonging to `entity`.
    /// Returns `None` when the entity does not have that component.
    pub fn get<T>(&self, entity: Entity) -> Option<&T>
    where
        T: Component + 'static,
    {
        self.get_store::<T>().get(entity)
    }

    /// Mutable reference to a component belonging to `entity`.
    /// Panics if the component store has never been created.
    pub fn get_mut<T>(&mut self, entity: Entity) -> Option<&mut T>
    where
        T: Component + 'static,
    {
        self.get_store_mut::<T>().get_mut(entity)
    }

    /// Check whether an entity has a component of type `T`.
    pub fn has<T>(&self, entity: Entity) -> bool
    where
        T: Component + 'static,
    {
        self.get_store::<T>().contains(entity)
    }

    /// Check whether an entity has any components in tuple `T`.
    pub fn has_any<T>(&self, entity: Entity) -> bool
    where
        T: HasAny,
    {
        T::has_any(self, entity)
    }

    /// Remove an entity and all of its descendants.
    pub fn remove_entity(ctx: &mut GameCtxMut, entity: Entity) {
        // Detach from parent (if any)
        if let Some(parent) = ctx.ecs.get::<Parent>(entity).map(|p| p.0)
            && let Some(children) = ctx.ecs.get_mut::<Children>(parent)
        {
            children.remove(entity);
            if children.entities.is_empty() {
                ctx.ecs.get_store_mut::<Children>().remove(parent);
            }
        }

        // Remove children recursively
        let children = get_children(ctx.ecs, entity);
        for child in children {
            Ecs::remove_entity(ctx, child);
        }

        // Remove all its components
        for reg in inventory::iter::<ComponentRegistry> {
            // Run post_remove for all components before removing them
            if (reg.has)(ctx.ecs, entity) {
                let mut boxed = (reg.clone)(ctx.ecs, entity);
                (reg.post_remove)(&mut *boxed, &entity, ctx);
            }

            (reg.remove)(ctx.ecs, entity);
        }
    }

    /// Remove a single component from an entity, calling its post_remove hook.
    pub fn remove_component<T>(ctx: &mut GameCtxMut, entity: Entity)
    where
        T: Component + 'static,
    {
        let type_name = std::any::type_name::<T>().rsplit("::").next().unwrap_or("");

        // Find the registry entry for this component type
        let reg = inventory::iter::<ComponentRegistry>
            .into_iter()
            .find(|r| r.type_name == type_name);

        if let Some(reg) = reg
            && (reg.has)(ctx.ecs, entity)
        {
            let mut boxed = (reg.clone)(ctx.ecs, entity);
            (reg.post_remove)(&mut *boxed, &entity, ctx);
            (reg.remove)(ctx.ecs, entity);
        }
    }

    // TODO: Is this legit?
    /// Return an immutable reference to the store for Component `T`.
    pub fn get_store<T>(&self) -> &ComponentStore<T>
    where
        T: Component + 'static,
    {
        unsafe {
            let mut_self = self as *const Self as *mut Self;
            (*mut_self).get_or_create_store::<T>()
        }
    }

    /// Return a mutable reference, creating the store on‑first‑use.
    pub fn get_store_mut<T>(&mut self) -> &mut ComponentStore<T>
    where
        T: Component + 'static,
    {
        self.get_or_create_store::<T>()
    }

    /// Used by the `Component` impl generated by the ecs_component macro.
    pub(crate) fn get_or_create_store<T>(&mut self) -> &mut ComponentStore<T>
    where
        T: Component + 'static,
    {
        let key = TypeId::of::<ComponentStore<T>>();

        self.stores
            .entry(key)
            .or_insert_with(|| Box::new(ComponentStore::<T>::default()));

        self.stores
            .get_mut(&key)
            .unwrap()
            .downcast_mut::<ComponentStore<T>>()
            .unwrap()
    }

    pub fn insert_component<T>(&mut self, entity: Entity, component: T)
    where
        T: Component + Serialize + for<'de> Deserialize<'de> + Clone + Default + 'static,
    {
        // Store in the typed store (engine code can still use it directly)
        self.get_store_mut::<T>().insert(entity, component.clone());
    }

    /// Insert a component on an existing entity.
    /// If the component already exists it will be overwritten.
    pub fn add_component_to_entity<T>(&mut self, entity: Entity, component: T)
    where
        T: Component + Serialize + for<'de> Deserialize<'de> + Clone + Default + 'static,
    {
        // Store it in the typed store – the same place the engine uses directly.
        self.get_store_mut::<T>().insert(entity, component);
    }

    /// Returns the player Entity if one exists.
    pub fn get_player_entity(&self) -> Option<Entity> {
        self.get_store::<Player>().data.keys().next().copied()
    }

    /// Returns the player Transform if a player exists.
    pub fn get_player_transform(&self) -> Option<Transform> {
        let player_entity = self.get_player_entity()?;

        self.get_store::<Transform>().get(player_entity).cloned()
    }

    /// Returns the player proxy for a given room, if one exists.
    pub fn get_player_proxy(&self, room_id: RoomId) -> Option<Entity> {
        let proxy_store = self.get_store::<PlayerProxy>();
        let room_store = self.get_store::<CurrentRoom>();

        proxy_store
            .data
            .keys()
            .find(|e| room_store.get(**e).is_some_and(|r| r.0 == room_id))
            .copied()
    }

    /// Sets the player's spawn position from the proxy in the given room.
    /// Call this before purging proxies to preserve the spawn location.
    pub fn set_player_spawn_from_proxy(&mut self, room_id: RoomId) {
        let spawn_pos = self
            .get_player_proxy(room_id)
            .and_then(|e| self.get::<Transform>(e))
            .map(|t| t.position);

        if let Some(pos) = spawn_pos
            && let Some(player_entity) = self.get_player_entity()
        {
            if let Some(transform) = self.get_mut::<Transform>(player_entity) {
                transform.position = pos;
            } else {
                self.add_component_to_entity(
                    player_entity,
                    Transform {
                        position: pos,
                        ..Default::default()
                    },
                );
            }
            self.add_component_to_entity(player_entity, CurrentRoom(room_id));
        }
    }

    /// Removes all PlayerProxy entities from the ECS.
    /// Used when preparing game data for playtest or export.
    pub fn purge_proxies(&mut self) {
        let proxy_entities: Vec<Entity> = self
            .get_store::<PlayerProxy>()
            .data
            .keys()
            .copied()
            .collect();

        for entity in proxy_entities {
            for reg in inventory::iter::<ComponentRegistry> {
                (reg.remove)(self, entity);
            }
        }
    }
}

impl Serialize for Ecs {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        // Build the dynamic component list
        let mut components = Vec::new();

        for (type_id, any_box) in &self.stores {
            // Find the registry entry that matches this TypeId
            let type_name = TYPE_NAME_FOR_ID.get(type_id);
            let type_name = match type_name {
                Some(name) => name,
                None => {
                    // Fallback
                    eprintln!(
                        "Skipping unknown component store (TypeId = {:?}) – \
                         it will not be saved. Add `ecs_component!` for the type to keep it.",
                        type_id
                    );
                    continue;
                }
            };
            let reg = inventory::iter::<ComponentRegistry>()
                .into_iter()
                .find(|r| r.type_name == *type_name)
                .expect("registry entry missing");

            // Convert the concrete store (`any_box`) into a RON value
            let ron_string = (reg.to_ron)(&**any_box);
            components.push(StoredComponent {
                type_name: reg.type_name.to_string(),
                data: ron_string,
            });
        }

        // Serialize the whole world
        let mut state = serializer.serialize_struct("Ecs", 2)?;
        state.serialize_field("components", &components)?;
        state.serialize_field("next_entity_id", &self.next_entity_id)?;
        state.end()
    }
}

impl<'de> Deserialize<'de> for Ecs {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        // Helper struct that mirrors the data that actually writes
        #[derive(Deserialize)]
        struct Helper {
            pub components: Vec<StoredComponent>,
            pub next_entity_id: usize,
        }

        let helper = Helper::deserialize(deserializer)?;

        // Rebuild the component map
        let mut stores = HashMap::new();
        for stored in &helper.components {
            // Try to find a registry entry
            let reg_opt =
                inventory::iter::<ComponentRegistry>().find(|r| r.type_name == stored.type_name);

            let reg = match reg_opt {
                Some(r) => r,
                None => {
                    // Unknown component
                    eprintln!(
                        "Skipping unknown component '{}' (probably removed or renamed).",
                        stored.type_name
                    );
                    continue;
                }
            };
            let any_box = (reg.from_ron)(stored.data.clone());
            let type_id = reg.type_id;
            stores.insert(type_id, any_box);
        }

        let ecs = Ecs {
            stores,
            next_entity_id: helper.next_entity_id,
        };

        Ok(ecs)
    }
}

static TYPE_NAME_FOR_ID: Lazy<HashMap<TypeId, &'static str>> = Lazy::new(|| {
    let mut map = HashMap::new();
    for reg in inventory::iter::<ComponentRegistry> {
        map.insert(reg.type_id, reg.type_name);
    }
    map
});
