// engine_core/src/ecs/reflect.rs
use macroquad::math::{Vec2, Vec3};

use crate::assets::sprite::SpriteId;

/// One mutable field value.
pub enum FieldValue<'a> {
    Text(&'a mut String),
    Float(&'a mut f32),
    Int(&'a mut i32),
    Bool(&'a mut bool),
    Vec2(&'a mut Vec2),
    Vec3(&'a mut Vec3),
    SpriteId(&'a mut SpriteId),
}

/// Metadata that the inspector consumes.
pub struct FieldInfo<'a> {
    pub name: &'static str,
    pub value: FieldValue<'a>,
    pub widget_hint: Option<&'static str>,
}

/// Trait that every component needs to expose.
pub trait Reflect {
    /// Returns a vector of mutable descriptors for all fields.
    fn fields(&mut self) -> Vec<FieldInfo<'_>>;
}

/// Helper trait
pub trait ReflectField {
    fn field_info<'a>(field: &'a mut Self, name: &'static str) -> FieldInfo<'a>;
}

/// Helper that attaches a hint to a `FieldInfo`.
impl<'a> FieldInfo<'a> {
    /// Consumes `self` and returns a new `FieldInfo` with the supplied hint.
    /// This method is **not** generated by the macro – it lives here once.
    pub fn with_hint(mut self, hint: Option<&'static str>) -> Self {
        self.widget_hint = hint;
        self
    }
}

impl ReflectField for String {
    fn field_info<'a>(field: &'a mut Self, name: &'static str) -> FieldInfo<'a> {
        FieldInfo { 
            name, 
            value: FieldValue::Text(field),
            widget_hint: None, 
        }
    }
}

impl ReflectField for f32 {
    fn field_info<'a>(field: &'a mut Self, name: &'static str) -> FieldInfo<'a> {
        FieldInfo { 
            name, 
            value: FieldValue::Float(field),
            widget_hint: None,
        }
    }
}

impl ReflectField for i32 {
    fn field_info<'a>(field: &'a mut Self, name: &'static str) -> FieldInfo<'a> {
        FieldInfo { 
            name, 
            value: FieldValue::Int(field),
            widget_hint: None, 
        }
    }
}

impl ReflectField for bool {
    fn field_info<'a>(field: &'a mut Self, name: &'static str) -> FieldInfo<'a> {
        FieldInfo { 
            name, 
            value: FieldValue::Bool(field),
            widget_hint: None 
        }
    }
}

impl ReflectField for Vec2 {
    fn field_info<'a>(field: &'a mut Self, name: &'static str) -> FieldInfo<'a> {
        FieldInfo { 
            name, 
            value: FieldValue::Vec2(field),
            widget_hint: None, 
        }
    }
}

impl ReflectField for Vec3 {
    fn field_info<'a>(field: &'a mut Self, name: &'static str) -> FieldInfo<'a> {
        FieldInfo { 
            name, 
            value: FieldValue::Vec3(field),
            widget_hint: None, 
        }
    }
}

impl ReflectField for SpriteId {
    fn field_info<'a>(field: &'a mut Self, name: &'static str) -> FieldInfo<'a> {
        FieldInfo { 
            name, 
            value: FieldValue::SpriteId(field),
            widget_hint: None, 
        }
    }
}