[package]
name = "core"
version = "0.1.0"
edition = "2024"

[dependencies]
macroquad = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_with = "3.14.0"
ron = "0.9"
uuid = { version = "1.18", features = ["serde", "v4"] }