# Lua api generation for both platforms
[tasks.generate-lua-api]
script = [
    "cd ..",
    "cargo run -p lua_api_gen",
]

# Mac
[tasks.build-game-mac]
script = [
    "cd ..",
    "cargo build -p game --release --target x86_64-apple-darwin",
]

[tasks.copy-game-bins-mac]
script = [
    "cd ..",
    "mkdir -p editor/binaries",
    "cp -f target/x86_64-apple-darwin/release/game editor/binaries/",
    "cp -f target/x86_64-apple-darwin/release/game-playtest editor/binaries/"
]
dependencies = ["build-game-mac"]

[tasks.build-editor-mac]
command = "cargo"
args = ["build", "--release", "--target", "x86_64-apple-darwin"]
dependencies = ["generate-lua-api", "copy-game-bins-mac"]

[tasks.release-editor-mac]
command = "cargo"
args = ["bundle", "--release", "--target", "x86_64-apple-darwin"]
dependencies = ["build-editor-mac"]

# Windows
[tasks.build-game-windows]
script = [
    "cd ..",
    "cargo build -p game --release --target x86_64-pc-windows-msvc",
]

[tasks.copy-game-exes-unix]
condition = { platforms = ["mac", "linux"]}
script = [
    "cd ..",
    "mkdir -p editor/binaries",
    "cp -f target/x86_64-pc-windows-msvc/release/game.exe editor/binaries/",
    "cp -f target/x86_64-pc-windows-msvc/release/game-playtest.exe editor/binaries/",
]
dependencies = ["build-game-windows"]

[tasks.copy-game-exes-windows]
condition = { platforms = ["windows"]}
script = [
    "cd ..",
    "mkdir editor\\binaries",
    "copy /Y target\\x86_64-pc-windows-msvc\\release\\game.exe editor\\binaries\\",
    "copy /Y target\\x86_64-pc-windows-msvc\\release\\game-playtest.exe editor\\binaries\\"
]
dependencies = ["build-game-windows"]

[tasks.release-editor-windows]
command = "cargo"
args = ["build", "--release", "--target", "x86_64-pc-windows-msvc"]
dependencies = [
    "generate-lua-api",
    "copy-game-exes-windows",
    "copy-game-exes-unix",
]