use super::{
    load_startup_for_game_name, load_startup_from_resources, StartupAsset,
    StartupScreenContent, StartupScreenSpec,
};
use crate::engine::{Engine, EngineBuilder, EngineEntryMode, GameInstance};
use bishop::prelude::*;
use engine_core::prelude::*;
use ron::de::from_str;
use std::fs;
use std::path::{Path, PathBuf};

/// The source for runtime startup.
pub enum StartupSource {
    /// Load the shipped game from the game binary's `Resources/` folder.
    Game,
    /// Load a playtest payload generated by the editor.
    Playtest {
        payload_path: String,
    },
}

#[derive(serde::Deserialize)]
struct PlaytestPayload {
    room: Room,
    game: Game,
    startup_ron: Option<String>,
    #[serde(default)]
    startup_mode: StartupMode,
}

enum LoadedStartupData {
    Game {
        startup_asset: StartupAsset,
        game: Game,
    },
    Playtest {
        startup_asset: StartupAsset,
        room: Room,
        game: Game,
        startup_mode: StartupMode,
    },
}

enum LoadedStartupFiles {
    Game {
        resources_dir: PathBuf,
        startup_ron: Option<String>,
        game_ron: String,
    },
    Playtest {
        payload_ron: String,
    },
}

/// Bootstrap controller that renders startup screens until the runtime `Engine` is ready.
pub struct StartupController {
    startup_asset: StartupAsset,
    load_task: BackgroundTask<Result<LoadedStartupFiles, String>>,
    loaded: Option<LoadedStartupData>,
    splash_index: usize,
    splash_started_at_secs: Option<f64>,
    fallback_started_at_secs: Option<f64>,
    error: Option<String>,
}

impl StartupController {
    /// Creates a startup controller for the given source.
    pub fn new(source: StartupSource) -> Self {
        let startup_asset = load_initial_startup(&source);
        Self {
            startup_asset,
            load_task: BackgroundTask::spawn(move || load_startup_data(source)),
            loaded: None,
            splash_index: 0,
            splash_started_at_secs: None,
            fallback_started_at_secs: None,
            error: None,
        }
    }

    /// Advances bootstrap and returns the fully-built engine once ready.
    pub async fn frame(&mut self, ctx: PlatformContext) -> Option<Engine> {
        if let Some(error) = &self.error {
            render_error_screen(&ctx, error);
            return None;
        }

        if self.loaded.is_none() {
            if let Some(result) = self.load_task.poll() {
                match result {
                    Ok(files) => match parse_startup_data(files) {
                        Ok(loaded) => {
                            self.startup_asset = loaded.startup_asset().clone();
                            self.loaded = Some(loaded);
                        }
                        Err(error) => self.error = Some(error),
                    },
                    Err(error) => {
                        self.error = Some(error);
                    }
                }
            }
        }

        if let Some(error) = &self.error {
            render_error_screen(&ctx, error);
            return None;
        }

        if self
            .loaded
            .as_ref()
            .is_some_and(LoadedStartupData::skips_startup_presentation)
        {
            let loaded = self.loaded.take()?;
            return Some(build_engine(ctx, loaded));
        }

        if let Some(screen) = self.startup_asset.loading.splash_screens.get(self.splash_index) {
            render_screen(&ctx, screen);
            let now = ctx.borrow().get_time();
            let started_at = self.splash_started_at_secs.get_or_insert(now);
            if splash_min_duration_elapsed(*started_at, now, screen.min_duration_secs) {
                self.splash_started_at_secs = None;
                self.splash_index += 1;
            }
            return None;
        }

        render_screen(&ctx, &self.startup_asset.loading.fallback_screen);

        let now = ctx.borrow().get_time();
        let started_at = self.fallback_started_at_secs.get_or_insert(now);
        if !splash_min_duration_elapsed(
            *started_at,
            now,
            self.startup_asset.loading.fallback_screen.min_duration_secs,
        ) {
            return None;
        }

        self.fallback_started_at_secs = None;
        let loaded = self.loaded.take()?;
        Some(build_engine(ctx, loaded))
    }
}

impl LoadedStartupData {
    fn startup_asset(&self) -> &StartupAsset {
        match self {
            Self::Game { startup_asset, .. } | Self::Playtest { startup_asset, .. } => startup_asset,
        }
    }

    fn skips_startup_presentation(&self) -> bool {
        matches!(
            self,
            Self::Playtest {
                startup_mode: StartupMode::Skip,
                ..
            }
        )
    }
}

fn load_startup_data(source: StartupSource) -> Result<LoadedStartupFiles, String> {
    match source {
        StartupSource::Game => {
            let resources_dir = resources_dir_from_exe()
                .ok_or_else(|| "Could not find game resources folder.".to_string())?;
            let startup_path = resources_dir.join("startup.ron");
            let startup_ron = fs::read_to_string(&startup_path).ok();
            let game_path = resources_dir.join(GAME_RON);
            let game_ron = fs::read_to_string(&game_path)
                .map_err(|error| format!("Could not read '{}': {error}", game_path.display()))?;
            Ok(LoadedStartupFiles::Game {
                resources_dir,
                startup_ron,
                game_ron,
            })
        }
        StartupSource::Playtest { payload_path } => {
            let payload_str = fs::read_to_string(&payload_path)
                .map_err(|error| format!("Could not read playtest payload: {error}"))?;
            Ok(LoadedStartupFiles::Playtest {
                payload_ron: payload_str,
            })
        }
    }
}

fn load_initial_startup(source: &StartupSource) -> StartupAsset {
    match source {
        StartupSource::Game => resources_dir_from_exe()
            .map(|resources_dir| load_startup_from_resources(&resources_dir))
            .unwrap_or_default(),
        StartupSource::Playtest { payload_path } => {
            load_playtest_startup_preview(Path::new(payload_path)).unwrap_or_default()
        }
    }
}

fn load_playtest_startup_preview(payload_path: &Path) -> Option<StartupAsset> {
    #[derive(serde::Deserialize)]
    struct PayloadGamePreview {
        game: PayloadGameName,
        startup_ron: Option<String>,
    }

    #[derive(serde::Deserialize)]
    struct PayloadGameName {
        name: String,
    }

    let payload_ron = fs::read_to_string(payload_path).ok()?;
    let preview = from_str::<PayloadGamePreview>(&payload_ron).ok()?;
    if let Some(startup_ron) = preview.startup_ron.as_deref() {
        return Some(parse_payload_startup(startup_ron));
    }
    Some(load_startup_for_game_name(&preview.game.name))
}

fn parse_startup_data(files: LoadedStartupFiles) -> Result<LoadedStartupData, String> {
    match files {
        LoadedStartupFiles::Game {
            resources_dir,
            startup_ron,
            game_ron,
        } => {
            let startup_asset = parse_startup(startup_ron.as_deref(), &resources_dir);
            let game =
                from_str::<Game>(&game_ron).map_err(|error| format!("Failed to parse game.ron: {error}"))?;
            Ok(LoadedStartupData::Game { startup_asset, game })
        }
        LoadedStartupFiles::Playtest { payload_ron } => {
            let PlaytestPayload {
                room,
                game,
                startup_ron,
                startup_mode,
            } = from_str(&payload_ron)
                .map_err(|error| format!("Failed to deserialize playtest payload: {error}"))?;
            let startup_asset = startup_ron
                .as_deref()
                .map(parse_payload_startup)
                .unwrap_or_else(|| load_startup_for_game_name(&game.name));
            Ok(LoadedStartupData::Playtest {
                startup_asset,
                room,
                game,
                startup_mode,
            })
        }
    }
}

fn parse_startup(startup_ron: Option<&str>, resources_dir: &Path) -> StartupAsset {
    let Some(startup_ron) = startup_ron else {
        return StartupAsset::default();
    };

    ron::from_str(startup_ron).unwrap_or_else(|error| {
        onscreen_error!(
            "Failed to parse startup '{}': {}",
            resources_dir.join("startup.ron").display(),
            error
        );
        StartupAsset::default()
    })
}

fn parse_payload_startup(startup_ron: &str) -> StartupAsset {
    ron::from_str(startup_ron).unwrap_or_else(|error| {
        onscreen_error!("Failed to parse embedded playtest startup: {}", error);
        StartupAsset::default()
    })
}

fn build_engine(ctx: PlatformContext, loaded: LoadedStartupData) -> Engine {
    match loaded {
        LoadedStartupData::Game { startup_asset, game } => {
            set_engine_mode(EngineMode::Game);
            set_game_name(game.name.clone());

            let entry_mode = resolve_entry_mode(&startup_asset, &game, StartupMode::Full);
            let mut builder = EngineBuilder::new().entry_mode(entry_mode);
            let game_instance = {
                let mut ctx_ref = ctx.borrow_mut();
                GameInstance::from_loaded_game(
                    &mut *ctx_ref,
                    game,
                    &builder.lua,
                    &mut builder.camera_manager,
                )
            };

            builder.assemble(game_instance, ctx, false)
        }
        LoadedStartupData::Playtest {
            startup_asset,
            room,
            game,
            startup_mode,
        } => {
            set_engine_mode(EngineMode::Playtest);
            set_game_name(game.name.clone());

            let entry_mode = resolve_entry_mode(&startup_asset, &game, startup_mode);
            let mut builder = EngineBuilder::new().entry_mode(entry_mode);
            let game_instance = {
                let mut ctx_ref = ctx.borrow_mut();
                GameInstance::from_loaded_room(
                    &mut *ctx_ref,
                    room,
                    game,
                    &builder.lua,
                    &mut builder.camera_manager,
                )
            };

            builder.assemble(game_instance, ctx, true)
        }
    }
}

fn resolve_entry_mode(startup_asset: &StartupAsset, game: &Game, startup_mode: StartupMode) -> EngineEntryMode {
    if startup_mode == StartupMode::Skip {
        return EngineEntryMode::Playing;
    }

    let menu_id = startup_asset.start_menu_id.trim();
    if menu_id.is_empty() {
        return EngineEntryMode::Playing;
    }

    if !menu_template_exists(menu_id) {
        onscreen_error!(
            "Startup menu '{}' is missing for game '{}'; falling back to Playing.",
            menu_id,
            game.name
        );
        return EngineEntryMode::Playing;
    }

    EngineEntryMode::StartMenu {
        menu_id: menu_id.to_string(),
    }
}

fn menu_template_exists(menu_id: &str) -> bool {
    let dir = menus_folder();
    let Ok(entries) = fs::read_dir(dir) else {
        return false;
    };

    for entry in entries.filter_map(Result::ok) {
        let path = entry.path();
        if path.extension().is_none_or(|ext| ext != "ron") {
            continue;
        }
        let Ok(ron_str) = fs::read_to_string(&path) else {
            continue;
        };
        let Ok(template) = ron::from_str::<MenuTemplate>(&ron_str) else {
            continue;
        };
        if template.id == menu_id {
            return true;
        }
    }

    false
}

fn render_error_screen(ctx: &PlatformContext, error: &str) {
    let screen = StartupScreenSpec {
        min_duration_secs: 0.0,
        background_color: [0.1, 0.0, 0.0, 1.0],
        content: StartupScreenContent::Text {
            text: error.to_string(),
            font_size: 32.0,
            color: [1.0, 0.9, 0.9, 1.0],
        },
    };
    render_screen(ctx, &screen);
}

fn render_screen(ctx: &PlatformContext, screen: &StartupScreenSpec) {
    let mut ctx_ref = ctx.borrow_mut();
    let ctx = &mut *ctx_ref;
    ctx.clear_background(screen.background_color.into());

    match &screen.content {
        StartupScreenContent::Text {
            text,
            font_size,
            color,
        } => draw_centered_text(ctx, text, *font_size, (*color).into()),
    }
}

fn draw_centered_text(ctx: &mut impl BishopContext, text: &str, font_size: f32, color: Color) {
    let dims = ctx.measure_text(text, font_size);
    let x = (ctx.screen_width() - dims.width) * 0.5;
    let y = (ctx.screen_height() + dims.height) * 0.5;
    ctx.draw_text(text, x, y, font_size, color);
}

fn splash_min_duration_elapsed(started_at_secs: f64, now_secs: f64, min_duration_secs: f32) -> bool {
    (now_secs - started_at_secs) >= min_duration_secs as f64
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::time::{SystemTime, UNIX_EPOCH};

    fn unique_name(prefix: &str) -> String {
        let nanos = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        format!("{prefix}-{nanos}")
    }

    #[test]
    fn playtest_startup_preview_loads_authored_splash_screens_from_payload_game_name() {
        let game_name = unique_name("PlaytestPreview");
        let game_dir = game_folder(&game_name);
        let resources_dir = game_dir.join(RESOURCES_FOLDER);
        fs::create_dir_all(&resources_dir).unwrap();
        let startup = StartupAsset {
            loading: super::super::LoadingConfig {
                splash_screens: vec![StartupScreenSpec {
                    min_duration_secs: 1.0,
                    background_color: [0.1, 0.2, 0.3, 1.0],
                    content: StartupScreenContent::Text {
                        text: "Splash".to_string(),
                        font_size: 42.0,
                        color: [1.0, 1.0, 1.0, 1.0],
                    },
                }],
                fallback_screen: StartupScreenSpec::default(),
            },
            start_menu_id: "start".to_string(),
        };
        fs::write(
            resources_dir.join("startup.ron"),
            ron::ser::to_string_pretty(&startup, ron::ser::PrettyConfig::new()).unwrap(),
        )
        .unwrap();

        let payload_path = std::env::temp_dir().join(format!("{}.ron", unique_name("payload")));
        fs::write(
            &payload_path,
            format!(
                r#"
(
    game: (
        name: "{game_name}",
    ),
)
"#
            ),
        )
        .unwrap();

        let startup = load_playtest_startup_preview(&payload_path).unwrap();

        assert_eq!(startup.loading.splash_screens.len(), 1);

        let _ = fs::remove_file(payload_path);
        let _ = fs::remove_dir_all(game_dir);
    }

    #[test]
    fn playtest_startup_preview_prefers_embedded_payload() {
        let game_name = unique_name("EmbeddedPlaytestPreview");
        let payload_path = std::env::temp_dir().join(format!("{}.ron", unique_name("payload")));
        let embedded_startup = StartupAsset {
            loading: super::super::LoadingConfig {
                splash_screens: vec![StartupScreenSpec {
                    min_duration_secs: 3.0,
                    background_color: [0.4, 0.3, 0.2, 1.0],
                    content: StartupScreenContent::Text {
                        text: "Embedded".to_string(),
                        font_size: 30.0,
                        color: [1.0, 1.0, 1.0, 1.0],
                    },
                }],
                fallback_screen: StartupScreenSpec::default(),
            },
            start_menu_id: "start".to_string(),
        };

        #[derive(serde::Serialize)]
        struct Payload<'a> {
            game: PayloadGame<'a>,
            startup_ron: Option<String>,
        }

        #[derive(serde::Serialize)]
        struct PayloadGame<'a> {
            name: &'a str,
        }

        fs::write(
            &payload_path,
            ron::ser::to_string_pretty(
                &Payload {
                    game: PayloadGame { name: &game_name },
                    startup_ron: Some(ron::ser::to_string_pretty(
                        &embedded_startup,
                        ron::ser::PrettyConfig::new(),
                    )
                    .unwrap()),
                },
                ron::ser::PrettyConfig::new(),
            )
            .unwrap(),
        )
        .unwrap();

        let startup = load_playtest_startup_preview(&payload_path).unwrap();

        assert_eq!(startup.loading.splash_screens.len(), 1);
        match &startup.loading.splash_screens[0].content {
            StartupScreenContent::Text { text, .. } => assert_eq!(text, "Embedded"),
        }

        let _ = fs::remove_file(payload_path);
    }

    #[test]
    fn splash_duration_starts_from_first_visible_frame() {
        assert!(!splash_min_duration_elapsed(10.0, 10.0, 1.5));
        assert!(!splash_min_duration_elapsed(10.0, 11.49, 1.5));
        assert!(splash_min_duration_elapsed(10.0, 11.5, 1.5));
    }

    #[test]
    fn fallback_min_duration_starts_from_first_visible_frame() {
        assert!(!splash_min_duration_elapsed(20.0, 20.0, 5.0));
        assert!(!splash_min_duration_elapsed(20.0, 24.99, 5.0));
        assert!(splash_min_duration_elapsed(20.0, 25.0, 5.0));
    }

    #[test]
    fn parse_startup_data_uses_startup_mode_from_payload() {
        let payload = r#"
(
    room: (
        name: "Room",
    ),
    game: (
        name: "Demo",
    ),
    startup_mode: Full,
)
"#;

        let loaded = parse_startup_data(LoadedStartupFiles::Playtest {
            payload_ron: payload.to_string(),
        })
        .unwrap();

        match loaded {
            LoadedStartupData::Playtest {
                startup_mode, ..
            } => assert_eq!(startup_mode, StartupMode::Full),
            LoadedStartupData::Game { .. } => panic!("expected playtest startup data"),
        }
    }

    #[test]
    fn playtest_skip_mode_bypasses_startup_presentation() {
        let loaded = LoadedStartupData::Playtest {
            startup_asset: StartupAsset::default(),
            room: Room::default(),
            game: Game::default(),
            startup_mode: StartupMode::Skip,
        };

        assert!(loaded.skips_startup_presentation());
    }
}
